# Generated by Django 3.0.2 on 2020-03-21 21:33

from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0006_permupload_mods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedupload',
            name='file',
            field=models.FileField(max_length=2048, storage=django_drf_filepond.models.FilePondStoredSystemStorage(), upload_to=''),
        ),
    ]
